[package]
name = "kafkrs-server"
version = "0.3.0"
edition = "2021"

[lib]
name = "kafkrs_server"
path = "src/lib.rs"

[[bin]]
name = "kafkrs-server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
tokio = { version = "1.37.0", features = [
  "fs",
  "rt",
  "rt-multi-thread",
  "macros",
  "signal",
  "sync",
  "io-util",
  "net",
  "time",
] }
toml = "0.8.12"
kafkrs-models = { path = "../kafkrs-models" }
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.198", features = ["derive"] }
# Dev
pre-commit-hooks = "0.3"
env_logger = "0.11"
arrow = "55.0.0"
arrow-schema = "55.0.0"
arrow-array = "55.0.0"
object_store = { version = "0.11", features = ["aws"] }
bytes = "1"
anyhow = "1"
serde_json = "1.0"
parquet = "55.0.0"
crc32c = "0.6"
prost = "0.14.3"
tokio-util = { version = "0.7.18", features = ["codec"] }
thiserror = "2.0.18"
tokio-stream = "0.1.18"

[dev-dependencies]
tempfile = "3"
