[package]
name = "kafkrs-models"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "55.0.0"
arrow-array = "55.0.0"
arrow-schema = "55.0.0"
chrono = { version = "0.4.38", features = ["serde"] }
crc32c = "0.6"
prost = "0.14.3"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
toml = "0.8.12"

[build-dependencies]
prost-build = "0.14.3"
protoc-bin-vendored = "3.2.0"
